export const wordList = [
  { english: "abolish", turkish: "iptal etmek", synonym: "eliminate", example: "The government decided to abolish the tax." },
  { english: "abolition", turkish: "kaldırmak", synonym: "dissolution", example: "They fought for the abolition of unfair laws." },
  { english: "absorb", turkish: "emmek", synonym: "soak up", example: "Sponges absorb water quickly." },
  { english: "abuse", turkish: "kötüye kullanma", synonym: "misuse", example: "He was warned not to abuse his power." },
  { english: "accelerator", turkish: "gaz pedalı", synonym: "throttle", example: "Press the accelerator to speed up." },
  { english: "accent", turkish: "aksan", synonym: "emphasis", example: "She speaks English with a French accent." },
  { english: "access", turkish: "giriş", synonym: "admittance", example: "You need a password to access the system." },
  { english: "accessible", turkish: "erişilebilir", synonym: "available", example: "The website is accessible from any phone." },
  { english: "accounting", turkish: "muhasebe", synonym: "bookkeeping", example: "She works in the accounting department." },
  { english: "accumulate", turkish: "toplamak", synonym: "gather", example: "Dust begins to accumulate on unused books." },
  { english: "accused", turkish: "sanık", synonym: "suspect", example: "The accused person denied all allegations." },
  { english: "accustom", turkish: "alıştırmak", synonym: "inure", example: "It takes time to accustom yourself to new food." },
  { english: "accustomed", turkish: "alışık", synonym: "usual", example: "He is accustomed to waking up early." },
  { english: "achieve", turkish: "başarmak", synonym: "fulfil", example: "Work hard to achieve your goals." },
  { english: "acknowledge", turkish: "doğrulamak", synonym: "recognize", example: "He refused to acknowledge his mistake." },
  { english: "acquire", turkish: "edinmek", synonym: "receive", example: "Scientists are trying to acquire the primary causes of this phenomenon." },
  { english: "acquisition", turkish: "edinme", synonym: "purchase", example: "The new policy addresses the impact of acquisition in modern society." },
  { english: "addict", turkish: "müptela", synonym: "dependent", example: "The new policy addresses the impact of addict in modern society." },
  { english: "admission", turkish: "kabul", synonym: "acknowledgment", example: "The new policy addresses the impact of admission in modern society." },
  { english: "adopt", turkish: "kabul etmek", synonym: "embrace", example: "Scientists are trying to adopt the primary causes of this phenomenon." },
  { english: "adverse", turkish: "zıt", synonym: "unfavorable", example: "The new policy addresses the impact of adverse in modern society." },
  { english: "allocate", turkish: "dağıtmak", synonym: "designate", example: "Scientists are trying to allocate the primary causes of this phenomenon." },
  { english: "allocations", turkish: "tahsisat", synonym: "allotment", example: "The new policy addresses the impact of allocations in modern society." },
  { english: "allowance", turkish: "harçlık", synonym: "ration", example: "It is essential to adopt a allowance perspective during the evaluation." },
  { english: "ally", turkish: "anlaşma", synonym: "combine", example: "The new policy addresses the impact of ally in modern society." },
  { english: "alter", turkish: "değiştirmek", synonym: "change", example: "Scientists are trying to alter the primary causes of this phenomenon." },
  { english: "amend", turkish: "düzelme", synonym: "revise", example: "The new policy addresses the impact of amend in modern society." },
  { english: "ample", turkish: "geniş", synonym: "enough", example: "The new policy addresses the impact of ample in modern society." },
  { english: "anchor", turkish: "çapa", synonym: "hook", example: "The new policy addresses the impact of anchor in modern society." },
  { english: "anger", turkish: "kızmak", synonym: "infuriate", example: "Scientists are trying to anger the primary causes of this phenomenon." },
  { english: "angle", turkish: "açı", synonym: "perspective", example: "The new policy addresses the impact of angle in modern society." },
  { english: "anticipate", turkish: "ön görmek", synonym: "expect", example: "Scientists are trying to anticipate the primary causes of this phenomenon." },
  { english: "anxiously", turkish: "endişeli olmak", synonym: "be in doubt", example: "Scientists are trying to anxiously the primary causes of this phenomenon." },
  { english: "apparently", turkish: "bariz olmak", synonym: "plainly", example: "Scientists are trying to apparently the primary causes of this phenomenon." },
  { english: "article of association", turkish: "ana sözleşme", synonym: "article of association", example: "The new policy addresses the impact of article of association in modern society." },
  { english: "aspect", turkish: "görünüş", synonym: "appearance", example: "The new policy addresses the impact of aspect in modern society." },
  { english: "asset", turkish: "varlık", synonym: "benefit", example: "It is essential to adopt a asset perspective during the evaluation." },
  { english: "association", turkish: "cemiyet", synonym: "federation", example: "The new policy addresses the impact of association in modern society." },
  { english: "assurance", turkish: "güven", synonym: "promise", example: "The new policy addresses the impact of assurance in modern society." },
  { english: "assure", turkish: "temin etmek", synonym: "provide", example: "Scientists are trying to assure the primary causes of this phenomenon." },
  { english: "assured", turkish: "önceden belli", synonym: "self-confident", example: "It is essential to adopt a assured perspective during the evaluation." },
  { english: "attachment", turkish: "ilave", synonym: "addition", example: "The new policy addresses the impact of attachment in modern society." },
  { english: "attendant", turkish: "hizmetçi", synonym: "servant", example: "The new policy addresses the impact of attendant in modern society." },
  { english: "auction", turkish: "müzayede", synonym: "trade", example: "The new policy addresses the impact of auction in modern society." },
  { english: "audience", turkish: "izleyici", synonym: "viewer", example: "The new policy addresses the impact of audience in modern society." },
  { english: "augment", turkish: "ilave etmek", synonym: "increase", example: "Scientists are trying to augment the primary causes of this phenomenon." },
  { english: "augmentation", turkish: "zam", synonym: "growth", example: "The new policy addresses the impact of augmentation in modern society." },
  { english: "author", turkish: "yazar", synonym: "writer", example: "The new policy addresses the impact of author in modern society." },
  { english: "authority", turkish: "otorite", synonym: "command", example: "The new policy addresses the impact of authority in modern society." },
  { english: "award", turkish: "mükafat", synonym: "offer", example: "The new policy addresses the impact of award in modern society." },
  { english: "awkward", turkish: "acemi", synonym: "incompetent", example: "The new policy addresses the impact of awkward in modern society." },
  { english: "babysitter", turkish: "çocuk bakıcısı", synonym: "babysitter", example: "The new policy addresses the impact of babysitter in modern society." },
  { english: "bachelor", turkish: "bekar", synonym: "single", example: "The new policy addresses the impact of bachelor in modern society." },
  { english: "backbone", turkish: "omurga", synonym: "spine", example: "The new policy addresses the impact of backbone in modern society." },
  { english: "bale", turkish: "balya", synonym: "bundle", example: "The new policy addresses the impact of bale in modern society." },
  { english: "banal", turkish: "adi", synonym: "trite", example: "The new policy addresses the impact of banal in modern society." },
  { english: "bandage", turkish: "yara bandı", synonym: "dressing", example: "The new policy addresses the impact of bandage in modern society." },
  { english: "baneful", turkish: "zararlı", synonym: "harmful", example: "It is essential to adopt a baneful perspective during the evaluation." },
  { english: "banish", turkish: "sürgün etmek", synonym: "exile", example: "Scientists are trying to banish the primary causes of this phenomenon." },
  { english: "barbarous", turkish: "barbar", synonym: "barbaric", example: "The new policy addresses the impact of barbarous in modern society." },
  { english: "barber", turkish: "berber", synonym: "hairdresser", example: "The new policy addresses the impact of barber in modern society." },
  { english: "basin", turkish: "leğen", synonym: "washtub", example: "The new policy addresses the impact of basin in modern society." },
  { english: "bastardize", turkish: "değerini düşürmek", synonym: "dejenere", example: "Scientists are trying to bastardize the primary causes of this phenomenon." },
  { english: "bawl", turkish: "bağırmak", synonym: "yell", example: "Scientists are trying to bawl the primary causes of this phenomenon." },
  { english: "beforehand", turkish: "önceden", synonym: "previously", example: "The new policy addresses the impact of beforehand in modern society." },
  { english: "bias", turkish: "ön yargı", synonym: "prejudice", example: "The new policy addresses the impact of bias in modern society." },
  { english: "bladder", turkish: "kese", synonym: "cystic", example: "The new policy addresses the impact of bladder in modern society." },
  { english: "blade", turkish: "ustura", synonym: "sword", example: "The new policy addresses the impact of blade in modern society." },
  { english: "blister", turkish: "kabarcık", synonym: "sore", example: "The new policy addresses the impact of blister in modern society." },
  { english: "blockade", turkish: "ablukaya alma", synonym: "siege", example: "The new policy addresses the impact of blockade in modern society." },
  { english: "blouse", turkish: "bluz", synonym: "frock", example: "The new policy addresses the impact of blouse in modern society." },
  { english: "boiler", turkish: "kazan", synonym: "kettle", example: "The new policy addresses the impact of boiler in modern society." },
  { english: "bolt", turkish: "sürgü", synonym: "slide", example: "The new policy addresses the impact of bolt in modern society." },
  { english: "bonnet", turkish: "çocuk başlığı", synonym: "hood", example: "The new policy addresses the impact of bonnet in modern society." },
  { english: "bony", turkish: "çok zayıf", synonym: "thin", example: "The new policy addresses the impact of bony in modern society." },
  { english: "booklet", turkish: "broşür", synonym: "brochure", example: "The new policy addresses the impact of booklet in modern society." },
  { english: "boom", turkish: "patlamak", synonym: "bang", example: "Scientists are trying to boom the primary causes of this phenomenon." },
  { english: "boot", turkish: "ayakkabı", synonym: "buskin", example: "The new policy addresses the impact of boot in modern society." },
  { english: "boring", turkish: "sıkıcı", synonym: "annoying", example: "The new policy addresses the impact of boring in modern society." },
  { english: "bother", turkish: "can sıkmak", synonym: "annoy", example: "Scientists are trying to bother the primary causes of this phenomenon." },
  { english: "bounce", turkish: "yansıtmak", synonym: "reflect", example: "Scientists are trying to bounce the primary causes of this phenomenon." },
  { english: "bound", turkish: "bağlı", synonym: "tied", example: "It is essential to adopt a bound perspective during the evaluation." },
  { english: "boundary", turkish: "sınır", synonym: "limit", example: "The new policy addresses the impact of boundary in modern society." },
  { english: "brake", turkish: "frenlemek", synonym: "brake", example: "Scientists are trying to brake the primary causes of this phenomenon." },
  { english: "branch", turkish: "şube", synonym: "department", example: "The new policy addresses the impact of branch in modern society." },
  { english: "brand", turkish: "marka", synonym: "seal", example: "The new policy addresses the impact of brand in modern society." },
  { english: "brand-new", turkish: "yeni model", synonym: "unused", example: "The new policy addresses the impact of brand-new in modern society." },
  { english: "break down", turkish: "çöküş", synonym: "decay", example: "The new policy addresses the impact of break down in modern society." },
  { english: "break-out", turkish: "aniden başlama", synonym: "break-out", example: "The new policy addresses the impact of break-out in modern society." },
  { english: "breast", turkish: "göğüs", synonym: "nipple", example: "The new policy addresses the impact of breast in modern society." },
  { english: "bribe", turkish: "rüşvet vermek", synonym: "bribe", example: "Scientists are trying to bribe the primary causes of this phenomenon." },
  { english: "bride", turkish: "gelin", synonym: "bride", example: "The new policy addresses the impact of bride in modern society." },
  { english: "briefcase", turkish: "iş çantası", synonym: "portfolio", example: "The new policy addresses the impact of briefcase in modern society." },
  { english: "brilliant", turkish: "akıllı", synonym: "bright", example: "It is essential to adopt a brilliant perspective during the evaluation." },
  { english: "brochure", turkish: "broşür", synonym: "booklet", example: "The new policy addresses the impact of brochure in modern society." },
  { english: "broken", turkish: "kırık", synonym: "defunct", example: "The new policy addresses the impact of broken in modern society." },
  { english: "broker", turkish: "komisyoncu", synonym: "agent", example: "The new policy addresses the impact of broker in modern society." },
  { english: "brooch", turkish: "broş", synonym: "pin", example: "The new policy addresses the impact of brooch in modern society." },
  { english: "brother-in-law", turkish: "kayınbirader", synonym: "brother-in-law", example: "The new policy addresses the impact of brother-in-law in modern society." },
  { english: "brow", turkish: "alın", synonym: "forehead", example: "The new policy addresses the impact of brow in modern society." },
  { english: "bucket", turkish: "kova", synonym: "pail", example: "The new policy addresses the impact of bucket in modern society." },
  { english: "bull", turkish: "boğa", synonym: "taurine", example: "The new policy addresses the impact of bull in modern society." },
  { english: "bullet", turkish: "mermi", synonym: "projectile", example: "The new policy addresses the impact of bullet in modern society." },
  { english: "bureau", turkish: "büro", synonym: "agency", example: "The new policy addresses the impact of bureau in modern society." },
  { english: "bureaucracy", turkish: "bürokrasi", synonym: "bureaucracy", example: "The new policy addresses the impact of bureaucracy in modern society." },
  { english: "by the way", turkish: "bu arada", synonym: "meanwhile", example: "The new policy addresses the impact of by the way in modern society." },
  { english: "cabbage", turkish: "lahana", synonym: "cabbage", example: "The new policy addresses the impact of cabbage in modern society." },
  { english: "cabin", turkish: "kabin", synonym: "hut", example: "The new policy addresses the impact of cabin in modern society." },
  { english: "cabinet", turkish: "kabine", synonym: "council", example: "The new policy addresses the impact of cabinet in modern society." },
  { english: "calf", turkish: "buzağı", synonym: "calf", example: "The new policy addresses the impact of calf in modern society." },
  { english: "camel", turkish: "deve", synonym: "camel", example: "The new policy addresses the impact of camel in modern society." },
  { english: "canary", turkish: "kanarya", synonym: "canary", example: "The new policy addresses the impact of canary in modern society." },
  { english: "cancellation", turkish: "iptal", synonym: "annulment", example: "The new policy addresses the impact of cancellation in modern society." },
  { english: "cannon", turkish: "top-silah", synonym: "gun", example: "The new policy addresses the impact of cannon in modern society." },
  { english: "capable", turkish: "yetenekli", synonym: "talented", example: "It is essential to adopt a capable perspective during the evaluation." },
  { english: "carbon-paper", turkish: "karbon kağıdı", synonym: "carbon-paper", example: "The new policy addresses the impact of carbon-paper in modern society." },
  { english: "carefree", turkish: "önemsemeyen", synonym: "insouciant", example: "The new policy addresses the impact of carefree in modern society." },
  { english: "careful", turkish: "dikkatli", synonym: "attentive", example: "It is essential to adopt a careful perspective during the evaluation." },
  { english: "careless", turkish: "dikkatsiz", synonym: "reckless", example: "It is essential to adopt a careless perspective during the evaluation." },
  { english: "cargo", turkish: "kargo", synonym: "cargo", example: "The new policy addresses the impact of cargo in modern society." },
  { english: "carrier", turkish: "taşıyıcı", synonym: "courier", example: "The new policy addresses the impact of carrier in modern society." },
  { english: "carrot", turkish: "havuç", synonym: "carrot", example: "The new policy addresses the impact of carrot in modern society." },
  { english: "carryover", turkish: "devir", synonym: "carryover", example: "The new policy addresses the impact of carryover in modern society." },
  { english: "cartridge", turkish: "kartuş", synonym: "cartridge", example: "The new policy addresses the impact of cartridge in modern society." },
  { english: "cash-register", turkish: "yazar kasa", synonym: "cash-register", example: "The new policy addresses the impact of cash-register in modern society." },
  { english: "casual", turkish: "gündelik", synonym: "ordinary", example: "It is essential to adopt a casual perspective during the evaluation." },
  { english: "caterpillar", turkish: "tırtıl", synonym: "miling", example: "The new policy addresses the impact of caterpillar in modern society." },
  { english: "cauliflower", turkish: "karnabahar", synonym: "cauliflower", example: "The new policy addresses the impact of cauliflower in modern society." },
  { english: "caution", turkish: "uyarı", synonym: "warning", example: "The new policy addresses the impact of caution in modern society." },
  { english: "cave", turkish: "mağara", synonym: "grotto", example: "The new policy addresses the impact of cave in modern society." },
  { english: "cease", turkish: "durdurmak", synonym: "stop", example: "Scientists are trying to cease the primary causes of this phenomenon." },
  { english: "cease-fire", turkish: "ateşkes", synonym: "cease-fire", example: "The new policy addresses the impact of cease-fire in modern society." },
  { english: "celebration", turkish: "kutlama", synonym: "ceremony", example: "The new policy addresses the impact of celebration in modern society." },
  { english: "cement", turkish: "çimento", synonym: "cement", example: "The new policy addresses the impact of cement in modern society." },
  { english: "central", turkish: "merkezi", synonym: "main", example: "The new policy addresses the impact of central in modern society." },
  { english: "centre", turkish: "merkez", synonym: "centre", example: "The new policy addresses the impact of centre in modern society." },
  { english: "cereal", turkish: "tahıl", synonym: "corny", example: "The new policy addresses the impact of cereal in modern society." },
  { english: "chamber", turkish: "oda", synonym: "chamber", example: "The new policy addresses the impact of chamber in modern society." },
  { english: "champagne", turkish: "şampanya", synonym: "champagne", example: "The new policy addresses the impact of champagne in modern society." },
  { english: "channel", turkish: "kanal", synonym: "channel", example: "The new policy addresses the impact of channel in modern society." },
  { english: "chapter", turkish: "bölüm", synonym: "part", example: "The new policy addresses the impact of chapter in modern society." },
  { english: "charity", turkish: "yardım severlik", synonym: "benevolence", example: "It is essential to adopt a charity perspective during the evaluation." },
  { english: "charlatan", turkish: "şarlatan", synonym: "charlatan", example: "The new policy addresses the impact of charlatan in modern society." },
  { english: "chart", turkish: "tablo", synonym: "table", example: "The new policy addresses the impact of chart in modern society." },
  { english: "charter", turkish: "patent", synonym: "patent", example: "The new policy addresses the impact of charter in modern society." },
  { english: "chase", turkish: "takip etmek", synonym: "pursue", example: "Scientists are trying to chase the primary causes of this phenomenon." },
  { english: "chat", turkish: "sohbet", synonym: "talk", example: "The new policy addresses the impact of chat in modern society." },
  { english: "cheek", turkish: "yanak", synonym: "cheek", example: "The new policy addresses the impact of cheek in modern society." },
  { english: "cheeky", turkish: "yüzsüz", synonym: "unabashed", example: "It is essential to adopt a cheeky perspective during the evaluation." },
  { english: "cheerful", turkish: "neşeli", synonym: "happy", example: "It is essential to adopt a cheerful perspective during the evaluation." },
  { english: "chef", turkish: "şef", synonym: "chef", example: "The new policy addresses the impact of chef in modern society." },
  { english: "cheque", turkish: "kontrol etmek", synonym: "cheque", example: "Scientists are trying to cheque the primary causes of this phenomenon." },
  { english: "chest", turkish: "göğüs", synonym: "thorax", example: "The new policy addresses the impact of chest in modern society." },
  { english: "chest of drawers", turkish: "çekmeceli dolap", synonym: "chest of drawers", example: "The new policy addresses the impact of chest of drawers in modern society." },
  { english: "chestnut", turkish: "kestane", synonym: "chestnut", example: "The new policy addresses the impact of chestnut in modern society." },
  { english: "chilli", turkish: "çok acı", synonym: "chilli", example: "The new policy addresses the impact of chilli in modern society." },
  { english: "chilly", turkish: "rahatsız edici soğuk", synonym: "cold", example: "The new policy addresses the impact of chilly in modern society." },
  { english: "chimney", turkish: "baca", synonym: "flue", example: "The new policy addresses the impact of chimney in modern society." },
  { english: "chip", turkish: "ufak parça", synonym: "chip", example: "The new policy addresses the impact of chip in modern society." },
  { english: "choice", turkish: "seçim", synonym: "selection", example: "The new policy addresses the impact of choice in modern society." },
  { english: "choke", turkish: "boğma", synonym: "drown", example: "The new policy addresses the impact of choke in modern society." },
  { english: "chop", turkish: "kesmek", synonym: "cut", example: "Scientists are trying to chop the primary causes of this phenomenon." },
  { english: "chuckle", turkish: "kıkırdama", synonym: "giggle", example: "The new policy addresses the impact of chuckle in modern society." },
  { english: "cigar", turkish: "puro", synonym: "cigar", example: "The new policy addresses the impact of cigar in modern society." },
  { english: "circuit", turkish: "devre", synonym: "loop", example: "The new policy addresses the impact of circuit in modern society." },
  { english: "claimant", turkish: "davacı", synonym: "plaintiff", example: "The new policy addresses the impact of claimant in modern society." },
  { english: "clap", turkish: "alkışlamak", synonym: "applaud", example: "Scientists are trying to clap the primary causes of this phenomenon." },
  { english: "clay", turkish: "kil", synonym: "mud", example: "The new policy addresses the impact of clay in modern society." },
  { english: "client", turkish: "müşteri", synonym: "customer", example: "The new policy addresses the impact of client in modern society." },
  { english: "climate", turkish: "iklim", synonym: "region", example: "The new policy addresses the impact of climate in modern society." },
  { english: "clinic", turkish: "klinik", synonym: "clinic", example: "The new policy addresses the impact of clinic in modern society." },
  { english: "clip", turkish: "kırpmak", synonym: "crop", example: "Scientists are trying to clip the primary causes of this phenomenon." },
  { english: "cloth", turkish: "bez", synonym: "cloth", example: "The new policy addresses the impact of cloth in modern society." },
  { english: "clown", turkish: "palyaço", synonym: "buffoon", example: "The new policy addresses the impact of clown in modern society." },
  { english: "clue", turkish: "ipucu", synonym: "sign", example: "The new policy addresses the impact of clue in modern society." },
  { english: "clutch", turkish: "debriyaj", synonym: "clutch", example: "The new policy addresses the impact of clutch in modern society." },
  { english: "co", turkish: "beraber", synonym: "co", example: "The new policy addresses the impact of co in modern society." },
  { english: "cooperate", turkish: "birlikte çalışmak", synonym: "work together", example: "Scientists are trying to cooperate the primary causes of this phenomenon." },
  { english: "coast", turkish: "kıyı", synonym: "shore", example: "The new policy addresses the impact of coast in modern society." },
  { english: "cock", turkish: "horoz", synonym: "cock", example: "The new policy addresses the impact of cock in modern society." },
  { english: "code", turkish: "kod", synonym: "code", example: "The new policy addresses the impact of code in modern society." },
  { english: "collapse", turkish: "çökmek", synonym: "cave in", example: "Scientists are trying to collapse the primary causes of this phenomenon." },
  { english: "colleague", turkish: "meslektaş", synonym: "colleague", example: "The new policy addresses the impact of colleague in modern society." },
  { english: "collective agreement", turkish: "toplu sözleşme", synonym: "collective agreement", example: "The new policy addresses the impact of collective agreement in modern society." },
  { english: "colonel", turkish: "albay", synonym: "colonel", example: "The new policy addresses the impact of colonel in modern society." },
  { english: "column", turkish: "sütun", synonym: "column", example: "The new policy addresses the impact of column in modern society." },
  { english: "coma", turkish: "koma", synonym: "coma", example: "The new policy addresses the impact of coma in modern society." },
  { english: "come across", turkish: "tesadüfen karşılaşmak", synonym: "meet by chance", example: "Scientists are trying to come across the primary causes of this phenomenon." },
  { english: "comet", turkish: "kuyruklu yıldız", synonym: "comet", example: "The new policy addresses the impact of comet in modern society." },
  { english: "commemorate", turkish: "anmak", synonym: "commemorate", example: "Scientists are trying to commemorate the primary causes of this phenomenon." },
  { english: "commission", turkish: "atamak", synonym: "employment", example: "Scientists are trying to commission the primary causes of this phenomenon." },
  { english: "commit", turkish: "suç işlemek", synonym: "sin", example: "Scientists are trying to commit the primary causes of this phenomenon." },
  { english: "commitment", turkish: "taahhüt", synonym: "pledge", example: "The new policy addresses the impact of commitment in modern society." },
  { english: "communicate", turkish: "iletişim", synonym: "communicate", example: "The new policy addresses the impact of communicate in modern society." },
  { english: "commute", turkish: "işe gidip gelmek", synonym: "commute", example: "Scientists are trying to commute the primary causes of this phenomenon." },
  { english: "compensate", turkish: "telafi etmek", synonym: "recompense", example: "Scientists are trying to compensate the primary causes of this phenomenon." },
  { english: "compensation", turkish: "telafi", synonym: "redress", example: "The new policy addresses the impact of compensation in modern society." },
  { english: "complicated", turkish: "komplike", synonym: "complex", example: "The new policy addresses the impact of complicated in modern society." },
  { english: "components", turkish: "unsur", synonym: "ingredient", example: "The new policy addresses the impact of components in modern society." },
  { english: "compose", turkish: "yapım", synonym: "compose", example: "The new policy addresses the impact of compose in modern society." },
  { english: "composition", turkish: "kompozisyon", synonym: "composition", example: "The new policy addresses the impact of composition in modern society." },
  { english: "compromise", turkish: "uzlaşma", synonym: "reconciliation", example: "The new policy addresses the impact of compromise in modern society." },
  { english: "concentrate", turkish: "konsantre", synonym: "concentrate", example: "The new policy addresses the impact of concentrate in modern society." },
  { english: "concept", turkish: "genel fikir", synonym: "opinion", example: "The new policy addresses the impact of concept in modern society." },
  { english: "concern", turkish: "kaygı", synonym: "anxiety", example: "The new policy addresses the impact of concern in modern society." },
  { english: "conclusion", turkish: "karar", synonym: "decision", example: "The new policy addresses the impact of conclusion in modern society." },
  { english: "condemn", turkish: "cezalandırmak", synonym: "doom", example: "Scientists are trying to condemn the primary causes of this phenomenon." },
  { english: "conduct", turkish: "davranış", synonym: "behavior", example: "The new policy addresses the impact of conduct in modern society." },
  { english: "cone", turkish: "koni", synonym: "cone", example: "The new policy addresses the impact of cone in modern society." },
  { english: "conference", turkish: "konferans", synonym: "meeting", example: "The new policy addresses the impact of conference in modern society." },
  { english: "confine", turkish: "kuşatmak", synonym: "blockade", example: "Scientists are trying to confine the primary causes of this phenomenon." },
  { english: "conflict", turkish: "çatışma", synonym: "clash", example: "The new policy addresses the impact of conflict in modern society." },
  { english: "consent", turkish: "kabul etmek", synonym: "accept", example: "Scientists are trying to consent the primary causes of this phenomenon." },
  { english: "consequently", turkish: "bundan dolayı", synonym: "therefore", example: "The new policy addresses the impact of consequently in modern society." },
  { english: "consistent", turkish: "tutarlı", synonym: "coherent", example: "It is essential to adopt a consistent perspective during the evaluation." },
  { english: "constitute", turkish: "oluşmak", synonym: "constitute", example: "Scientists are trying to constitute the primary causes of this phenomenon." },
  { english: "constitution", turkish: "anayasa", synonym: "constitution", example: "The new policy addresses the impact of constitution in modern society." },
  { english: "construct", turkish: "inşa etmek", synonym: "build", example: "Scientists are trying to construct the primary causes of this phenomenon." },
  { english: "consume", turkish: "tüketmek", synonym: "use up", example: "Scientists are trying to consume the primary causes of this phenomenon." },
  { english: "consumption", turkish: "tüketim", synonym: "consumption", example: "The new policy addresses the impact of consumption in modern society." },
  { english: "contact", turkish: "temas", synonym: "contiguity", example: "The new policy addresses the impact of contact in modern society." },
  { english: "contest", turkish: "yarışma", synonym: "competition", example: "The new policy addresses the impact of contest in modern society." },
  { english: "continent", turkish: "kıta", synonym: "mainland", example: "The new policy addresses the impact of continent in modern society." },
  { english: "contract", turkish: "anlaşma", synonym: "agreement", example: "The new policy addresses the impact of contract in modern society." },
  { english: "contribute", turkish: "katkıda bulunmak", synonym: "conduce", example: "Scientists are trying to contribute the primary causes of this phenomenon." },
  { english: "convict", turkish: "mahkum", synonym: "lag", example: "The new policy addresses the impact of convict in modern society." },
  { english: "convince", turkish: "ikna etmek", synonym: "persuade", example: "Scientists are trying to convince the primary causes of this phenomenon." },
  { english: "cope", turkish: "başa çıkmak", synonym: "get over", example: "Scientists are trying to cope the primary causes of this phenomenon." },
  { english: "cordon", turkish: "kordon", synonym: "cordon", example: "The new policy addresses the impact of cordon in modern society." },
  { english: "cork", turkish: "mantar", synonym: "mushroom", example: "The new policy addresses the impact of cork in modern society." },
  { english: "corpse", turkish: "ceset", synonym: "stiff", example: "The new policy addresses the impact of corpse in modern society." },
  { english: "correspondent", turkish: "mektuplaşan", synonym: "correspondent", example: "Scientists are trying to correspondent the primary causes of this phenomenon." },
  { english: "corridor", turkish: "korider", synonym: "corridor", example: "The new policy addresses the impact of corridor in modern society." },
  { english: "corruption", turkish: "rüşvetçilik", synonym: "corruption", example: "It is essential to adopt a corruption perspective during the evaluation." },
  { english: "cosmetic", turkish: "kozmetik", synonym: "cosmetic", example: "The new policy addresses the impact of cosmetic in modern society." },
  { english: "costume", turkish: "kostüm", synonym: "costume", example: "The new policy addresses the impact of costume in modern society." },
  { english: "coupe", turkish: "spor araba", synonym: "coupe", example: "The new policy addresses the impact of coupe in modern society." },
  { english: "coupon", turkish: "kupon", synonym: "coupon", example: "The new policy addresses the impact of coupon in modern society." },
  { english: "cracker", turkish: "kraker", synonym: "cracker", example: "The new policy addresses the impact of cracker in modern society." },
  { english: "cramp", turkish: "kramp", synonym: "cramp", example: "The new policy addresses the impact of cramp in modern society." },
  { english: "crane", turkish: "vinç", synonym: "crane", example: "The new policy addresses the impact of crane in modern society." },
  { english: "credit", turkish: "kredi", synonym: "credit", example: "The new policy addresses the impact of credit in modern society." },
  { english: "crisis", turkish: "kriz", synonym: "crisis", example: "The new policy addresses the impact of crisis in modern society." },
  { english: "crisp", turkish: "cips", synonym: "crisp", example: "The new policy addresses the impact of crisp in modern society." },
  { english: "critical", turkish: "kritik", synonym: "critical", example: "The new policy addresses the impact of critical in modern society." },
  { english: "crocodile", turkish: "timsah", synonym: "crocodile", example: "The new policy addresses the impact of crocodile in modern society." },
  { english: "crossword", turkish: "çapraz bulmaca", synonym: "crossword", example: "The new policy addresses the impact of crossword in modern society." },
  { english: "crucial", turkish: "en önemli an", synonym: "critical", example: "The new policy addresses the impact of crucial in modern society." },
  { english: "crude", turkish: "petrol", synonym: "gasoline", example: "The new policy addresses the impact of crude in modern society." },
  { english: "curry", turkish: "hafif acılı", synonym: "curry", example: "It is essential to adopt a curry perspective during the evaluation." },
  { english: "cushion", turkish: "yastık", synonym: "pillow", example: "The new policy addresses the impact of cushion in modern society." },
  { english: "cylinder", turkish: "silindir", synonym: "cylinder", example: "The new policy addresses the impact of cylinder in modern society." },
  { english: "daisy", turkish: "papatya", synonym: "daisy", example: "The new policy addresses the impact of daisy in modern society." },
  { english: "damage", turkish: "zarar", synonym: "hurt", example: "The new policy addresses the impact of damage in modern society." },
  { english: "darling", turkish: "sevgili", synonym: "darling", example: "It is essential to adopt a darling perspective during the evaluation." },
  { english: "date", turkish: "randevu", synonym: "date", example: "The new policy addresses the impact of date in modern society." },
  { english: "deadline", turkish: "mühlet", synonym: "deadline", example: "The new policy addresses the impact of deadline in modern society." },
  { english: "deadlock", turkish: "çıkmaz", synonym: "impasse", example: "The new policy addresses the impact of deadlock in modern society." },
  { english: "deaf", turkish: "sağır", synonym: "muted", example: "The new policy addresses the impact of deaf in modern society." },
  { english: "debatable", turkish: "tartışılabilir", synonym: "arguable", example: "The new policy addresses the impact of debatable in modern society." },
  { english: "debate", turkish: "tartışma", synonym: "discussion", example: "The new policy addresses the impact of debate in modern society." },
  { english: "debt", turkish: "borç", synonym: "loan", example: "The new policy addresses the impact of debt in modern society." },
  { english: "decay", turkish: "çürümek", synonym: "decay", example: "Scientists are trying to decay the primary causes of this phenomenon." },
  { english: "decent", turkish: "haklı", synonym: "decent", example: "It is essential to adopt a decent perspective during the evaluation." },
  { english: "decline", turkish: "azaltmak", synonym: "decrease", example: "Scientists are trying to decline the primary causes of this phenomenon." },
  { english: "decrease", turkish: "azalmak", synonym: "decline", example: "Scientists are trying to decrease the primary causes of this phenomenon." },
  { english: "default", turkish: "varsayılan", synonym: "default", example: "The new policy addresses the impact of default in modern society." },
  { english: "defer", turkish: "geciktirme", synonym: "delay", example: "The new policy addresses the impact of defer in modern society." },
  { english: "deficit", turkish: "açık", synonym: "shortage", example: "The new policy addresses the impact of deficit in modern society." },
  { english: "definition", turkish: "tanımlama", synonym: "description", example: "The new policy addresses the impact of definition in modern society." },
  { english: "deliberately", turkish: "kasten", synonym: "intentionally", example: "The new policy addresses the impact of deliberately in modern society." },
  { english: "demoralize", turkish: "moral bozmak", synonym: "dispirit", example: "Scientists are trying to demoralize the primary causes of this phenomenon." },
  { english: "dependent", turkish: "bağımlı", synonym: "dependent", example: "It is essential to adopt a dependent perspective during the evaluation." },
  { english: "deputation", turkish: "vekillik", synonym: "deputation", example: "It is essential to adopt a deputation perspective during the evaluation." },
  { english: "deputy", turkish: "vekil", synonym: "proxy", example: "The new policy addresses the impact of deputy in modern society." },
  { english: "desperate", turkish: "umutsuz", synonym: "hopeless", example: "It is essential to adopt a desperate perspective during the evaluation." },
  { english: "despite", turkish: "rağmen", synonym: "considering", example: "The new policy addresses the impact of despite in modern society." },
  { english: "destination", turkish: "varış noktası", synonym: "destination", example: "The new policy addresses the impact of destination in modern society." },
  { english: "detach", turkish: "ayırmak", synonym: "separate", example: "Scientists are trying to detach the primary causes of this phenomenon." },
  { english: "detective", turkish: "dedektif", synonym: "detective", example: "The new policy addresses the impact of detective in modern society." },
  { english: "dew", turkish: "kırağı", synonym: "dew", example: "The new policy addresses the impact of dew in modern society." },
  { english: "diagram", turkish: "şema", synonym: "schema", example: "The new policy addresses the impact of diagram in modern society." },
  { english: "diameter", turkish: "çap", synonym: "diameter", example: "The new policy addresses the impact of diameter in modern society." },
  { english: "dice", turkish: "zarlar", synonym: "dice", example: "The new policy addresses the impact of dice in modern society." },
  { english: "diet", turkish: "rejim", synonym: "diet", example: "The new policy addresses the impact of diet in modern society." },
  { english: "digest", turkish: "olayı kavramak", synonym: "clutch", example: "Scientists are trying to digest the primary causes of this phenomenon." },
  { english: "dim", turkish: "kısık", synonym: "uninspiring", example: "The new policy addresses the impact of dim in modern society." },
  { english: "dip", turkish: "daldırmak", synonym: "immerse", example: "Scientists are trying to dip the primary causes of this phenomenon." },
  { english: "directory", turkish: "rehber", synonym: "directory", example: "The new policy addresses the impact of directory in modern society." },
  { english: "disaster", turkish: "felaket", synonym: "calamity", example: "The new policy addresses the impact of disaster in modern society." },
  { english: "disclose", turkish: "meydana çıkarmak", synonym: "uncover", example: "Scientists are trying to disclose the primary causes of this phenomenon." },
  { english: "disgust", turkish: "tiksinti", synonym: "distaste", example: "The new policy addresses the impact of disgust in modern society." },
  { english: "dismay", turkish: "dehşet", synonym: "horror", example: "The new policy addresses the impact of dismay in modern society." },
  { english: "dispatch", turkish: "sevk etmek", synonym: "forward", example: "Scientists are trying to dispatch the primary causes of this phenomenon." },
  { english: "displace", turkish: "yerinden çıkarmak", synonym: "dislocate", example: "Scientists are trying to displace the primary causes of this phenomenon." },
  { english: "distinction", turkish: "küçük farklılık", synonym: "difference", example: "It is essential to adopt a distinction perspective during the evaluation." },
  { english: "dive", turkish: "dalış", synonym: "plunge", example: "The new policy addresses the impact of dive in modern society." },
  { english: "diver", turkish: "dalgıç", synonym: "diver", example: "The new policy addresses the impact of diver in modern society." },
  { english: "divorce", turkish: "boşanmak", synonym: "be loosed", example: "Scientists are trying to divorce the primary causes of this phenomenon." },
  { english: "dominate", turkish: "hakim olma", synonym: "dominate", example: "The new policy addresses the impact of dominate in modern society." },
  { english: "donor", turkish: "bağış yapan", synonym: "donor", example: "The new policy addresses the impact of donor in modern society." },
  { english: "doom", turkish: "kötü kader", synonym: "bad luck", example: "The new policy addresses the impact of doom in modern society." },
  { english: "doomsday", turkish: "ahiret günü", synonym: "doomsday", example: "The new policy addresses the impact of doomsday in modern society." },
  { english: "dose", turkish: "doz", synonym: "dose", example: "The new policy addresses the impact of dose in modern society." },
  { english: "down payment", turkish: "peşin", synonym: "prepayment", example: "The new policy addresses the impact of down payment in modern society." },
  { english: "doze", turkish: "uyuklamak", synonym: "slumber", example: "Scientists are trying to doze the primary causes of this phenomenon." },
  { english: "dozen", turkish: "düzine", synonym: "dozen", example: "The new policy addresses the impact of dozen in modern society." },
  { english: "draft", turkish: "suret", synonym: "draft", example: "The new policy addresses the impact of draft in modern society." },
  { english: "drag", turkish: "sürüklemek", synonym: "sweep", example: "Scientists are trying to drag the primary causes of this phenomenon." },
  { english: "drain", turkish: "lağım", synonym: "sewer", example: "The new policy addresses the impact of drain in modern society." },
  { english: "draught", turkish: "hava akımı", synonym: "draught", example: "The new policy addresses the impact of draught in modern society." },
  { english: "draughts", turkish: "dama oyunu", synonym: "draughts", example: "The new policy addresses the impact of draughts in modern society." },
  { english: "drawer", turkish: "çekmece", synonym: "drawer", example: "The new policy addresses the impact of drawer in modern society." },
  { english: "drawn", turkish: "boğulmak", synonym: "drawn", example: "Scientists are trying to drawn the primary causes of this phenomenon." },
  { english: "drug", turkish: "uyuşturucu madde", synonym: "drug", example: "The new policy addresses the impact of drug in modern society." },
  { english: "drum", turkish: "davul", synonym: "drum", example: "The new policy addresses the impact of drum in modern society." },
  { english: "duckling", turkish: "küçük ördek", synonym: "duckling", example: "The new policy addresses the impact of duckling in modern society." },
  { english: "duel", turkish: "düello", synonym: "duel", example: "The new policy addresses the impact of duel in modern society." },
  { english: "dustbin", turkish: "çöp tenekesi", synonym: "dustbin", example: "The new policy addresses the impact of dustbin in modern society." },
  { english: "dye", turkish: "boya", synonym: "paint", example: "The new policy addresses the impact of dye in modern society." },
  { english: "dynasty", turkish: "hanedanlık", synonym: "dynasty", example: "It is essential to adopt a dynasty perspective during the evaluation." },
  { english: "eagle", turkish: "kartal", synonym: "eagle", example: "The new policy addresses the impact of eagle in modern society." },
  { english: "earthquake", turkish: "deprem", synonym: "earthquake", example: "The new policy addresses the impact of earthquake in modern society." },
  { english: "eel", turkish: "yılan balığı", synonym: "eel", example: "The new policy addresses the impact of eel in modern society." },
  { english: "elapse", turkish: "zamanın geçmesi", synonym: "elapse", example: "The new policy addresses the impact of elapse in modern society." },
  { english: "embark", turkish: "yola çıkmak", synonym: "embark", example: "Scientists are trying to embark the primary causes of this phenomenon." },
  { english: "embarrassment", turkish: "sıkıntı", synonym: "distress", example: "The new policy addresses the impact of embarrassment in modern society." },
  { english: "embrace", turkish: "sarılmak", synonym: "hug", example: "Scientists are trying to embrace the primary causes of this phenomenon." },
  { english: "emotion", turkish: "duygu", synonym: "emotion", example: "The new policy addresses the impact of emotion in modern society." },
  { english: "emphasis", turkish: "önemli", synonym: "emphasis", example: "It is essential to adopt a emphasis perspective during the evaluation." },
  { english: "emphasize", turkish: "üzerinde durmak", synonym: "accentuate", example: "Scientists are trying to emphasize the primary causes of this phenomenon." },
  { english: "emphatic", turkish: "kesinlik", synonym: "important", example: "It is essential to adopt a emphatic perspective during the evaluation." },
  { english: "enormous", turkish: "kocaman", synonym: "imposing", example: "The new policy addresses the impact of enormous in modern society." },
  { english: "antitle", turkish: "yetki vermek", synonym: "authorize", example: "Scientists are trying to antitle the primary causes of this phenomenon." },
  { english: "epitaph", turkish: "mezartaşı yazısı", synonym: "epitaph", example: "The new policy addresses the impact of epitaph in modern society." },
  { english: "equalize", turkish: "eşitlemek", synonym: "equalize", example: "Scientists are trying to equalize the primary causes of this phenomenon." },
  { english: "equip", turkish: "donatmak", synonym: "equip", example: "Scientists are trying to equip the primary causes of this phenomenon." },
  { english: "equipment", turkish: "donanım", synonym: "equipment", example: "The new policy addresses the impact of equipment in modern society." },
  { english: "escort", turkish: "konvoy", synonym: "escort", example: "The new policy addresses the impact of escort in modern society." },
  { english: "estate", turkish: "malk mülk", synonym: "property", example: "The new policy addresses the impact of estate in modern society." },
  { english: "evacuate", turkish: "boşaltma", synonym: "discharge", example: "The new policy addresses the impact of evacuate in modern society." },
  { english: "evidence", turkish: "delil", synonym: "evidence", example: "The new policy addresses the impact of evidence in modern society." },
  { english: "evolution", turkish: "evrim", synonym: "evolution", example: "The new policy addresses the impact of evolution in modern society." },
  { english: "ex", turkish: "eski", synonym: "old", example: "The new policy addresses the impact of ex in modern society." },
  { english: "exceed", turkish: "aşırı", synonym: "over", example: "The new policy addresses the impact of exceed in modern society." },
  { english: "exclaim", turkish: "bağırmak", synonym: "yell", example: "Scientists are trying to exclaim the primary causes of this phenomenon." },
  { english: "execute", turkish: "yerine getirmek", synonym: "fulfill", example: "Scientists are trying to execute the primary causes of this phenomenon." },
  { english: "exhaust", turkish: "yorulma", synonym: "fatigue", example: "The new policy addresses the impact of exhaust in modern society." },
  { english: "exhibit", turkish: "göstermek", synonym: "show", example: "Scientists are trying to exhibit the primary causes of this phenomenon." },
  { english: "exhibition", turkish: "sergi", synonym: "showing", example: "The new policy addresses the impact of exhibition in modern society." },
  { english: "expand", turkish: "büyümek", synonym: "grow up", example: "Scientists are trying to expand the primary causes of this phenomenon." },
  { english: "expansion", turkish: "genişleme", synonym: "enlargement", example: "The new policy addresses the impact of expansion in modern society." },
  { english: "experiment", turkish: "deney", synonym: "test", example: "The new policy addresses the impact of experiment in modern society." },
  { english: "expire", turkish: "sürenin dolması", synonym: "expire", example: "The new policy addresses the impact of expire in modern society." },
  { english: "explosive", turkish: "patlayıcı madde", synonym: "explosive", example: "The new policy addresses the impact of explosive in modern society." },
  { english: "export", turkish: "ihracat", synonym: "export", example: "The new policy addresses the impact of export in modern society." },
  { english: "extinguish", turkish: "ateşi söndürmek", synonym: "extinguish", example: "Scientists are trying to extinguish the primary causes of this phenomenon." },
  { english: "extreme", turkish: "aşırı", synonym: "exceed", example: "The new policy addresses the impact of extreme in modern society." },
  { english: "eyebrow", turkish: "kaş", synonym: "eyebrow", example: "The new policy addresses the impact of eyebrow in modern society." },
  { english: "eyelash", turkish: "kirpik", synonym: "eyelash", example: "The new policy addresses the impact of eyelash in modern society." },
  { english: "eyelid", turkish: "göz kapağı", synonym: "eyelid", example: "The new policy addresses the impact of eyelid in modern society." },
  { english: "fable", turkish: "masal", synonym: "fable", example: "It is essential to adopt a fable perspective during the evaluation." },
  { english: "fabulous", turkish: "harika", synonym: "wonderful", example: "The new policy addresses the impact of fabulous in modern society." },
  { english: "fact", turkish: "gerçek", synonym: "truth", example: "The new policy addresses the impact of fact in modern society." },
  { english: "fake", turkish: "taklit", synonym: "counterfeit", example: "The new policy addresses the impact of fake in modern society." },
  { english: "fame", turkish: "şöhret", synonym: "reputation", example: "The new policy addresses the impact of fame in modern society." },
  { english: "fan", turkish: "taraftar", synonym: "fan", example: "The new policy addresses the impact of fan in modern society." },
  { english: "fancy", turkish: "hayal kurma", synonym: "to dream", example: "The new policy addresses the impact of fancy in modern society." },
  { english: "feature", turkish: "özellik", synonym: "property", example: "It is essential to adopt a feature perspective during the evaluation." },
  { english: "fed up", turkish: "bıkmak", synonym: "fed up", example: "Scientists are trying to fed up the primary causes of this phenomenon." },
  { english: "ferry", turkish: "feribot", synonym: "ferry", example: "The new policy addresses the impact of ferry in modern society." },
  { english: "fertile", turkish: "gübre", synonym: "fertile", example: "The new policy addresses the impact of fertile in modern society." },
  { english: "fertilize", turkish: "gübreleme", synonym: "fetilizer", example: "The new policy addresses the impact of fertilize in modern society." },
  { english: "fiance", turkish: "nişanlı", synonym: "fiance", example: "It is essential to adopt a fiance perspective during the evaluation." },
  { english: "fiction", turkish: "kurgu", synonym: "editing", example: "The new policy addresses the impact of fiction in modern society." },
  { english: "fig", turkish: "incir", synonym: "fig", example: "The new policy addresses the impact of fig in modern society." },
  { english: "fire-brigade", turkish: "itfaiye", synonym: "fire-brigade", example: "The new policy addresses the impact of fire-brigade in modern society." },
  { english: "fiscal", turkish: "mali", synonym: "financial", example: "It is essential to adopt a fiscal perspective during the evaluation." },
  { english: "fist", turkish: "yumruk", synonym: "punch", example: "The new policy addresses the impact of fist in modern society." },
  { english: "flea", turkish: "pire", synonym: "flea", example: "The new policy addresses the impact of flea in modern society." },
  { english: "flee", turkish: "kaçmak", synonym: "escape", example: "Scientists are trying to flee the primary causes of this phenomenon." },
  { english: "fleet", turkish: "filo", synonym: "fleet", example: "The new policy addresses the impact of fleet in modern society." },
  { english: "flipper", turkish: "yüzgeç", synonym: "flipper", example: "The new policy addresses the impact of flipper in modern society." },
  { english: "florist", turkish: "çiçekçi", synonym: "florist", example: "The new policy addresses the impact of florist in modern society." },
  { english: "fluent", turkish: "akıcı", synonym: "flowing", example: "The new policy addresses the impact of fluent in modern society." },
  { english: "foam", turkish: "köpük", synonym: "foam", example: "The new policy addresses the impact of foam in modern society." },
  { english: "foam rubber", turkish: "sünger", synonym: "sponge", example: "The new policy addresses the impact of foam rubber in modern society." },
  { english: "folk", turkish: "halk", synonym: "public", example: "The new policy addresses the impact of folk in modern society." },
  { english: "footprint", turkish: "ayak izi", synonym: "footprint", example: "The new policy addresses the impact of footprint in modern society." },
  { english: "foreman", turkish: "ustabaşı", synonym: "foreman", example: "The new policy addresses the impact of foreman in modern society." },
  { english: "forever", turkish: "devamlı olarak", synonym: "regularly", example: "The new policy addresses the impact of forever in modern society." },
  { english: "forge", turkish: "sahtesini yapmak", synonym: "counterfeit", example: "Scientists are trying to forge the primary causes of this phenomenon." },
  { english: "forger", turkish: "taklitçi", synonym: "copycat", example: "The new policy addresses the impact of forger in modern society." },
  { english: "formal", turkish: "resmi", synonym: "official", example: "The new policy addresses the impact of formal in modern society." },
  { english: "forthwith", turkish: "derhal", synonym: "immediately", example: "The new policy addresses the impact of forthwith in modern society." },
  { english: "foul", turkish: "pis", synonym: "dirty", example: "The new policy addresses the impact of foul in modern society." },
  { english: "found", turkish: "inşa etmek", synonym: "set up", example: "Scientists are trying to found the primary causes of this phenomenon." },
  { english: "fragile", turkish: "kolay kırılabilir", synonym: "brittle", example: "The new policy addresses the impact of fragile in modern society." },
  { english: "frank", turkish: "açık sözlü", synonym: "outspoken", example: "It is essential to adopt a frank perspective during the evaluation." },
  { english: "fridge", turkish: "buzdolabı", synonym: "fridge", example: "The new policy addresses the impact of fridge in modern society." },
  { english: "frontier", turkish: "sınır", synonym: "border", example: "The new policy addresses the impact of frontier in modern society." },
  { english: "fry", turkish: "kızartmak", synonym: "fry", example: "Scientists are trying to fry the primary causes of this phenomenon." },
  { english: "full stop", turkish: "nokta", synonym: "dot", example: "The new policy addresses the impact of full stop in modern society." },
  { english: "fundamental", turkish: "temel", synonym: "main", example: "The new policy addresses the impact of fundamental in modern society." },
  { english: "funeral", turkish: "cenaze", synonym: "funeral", example: "The new policy addresses the impact of funeral in modern society." },
  { english: "furthermore", turkish: "ayrıca", synonym: "also", example: "The new policy addresses the impact of furthermore in modern society." },
  { english: "fuse", turkish: "sigorta", synonym: "insurance", example: "The new policy addresses the impact of fuse in modern society." },
  { english: "fuss", turkish: "telaş", synonym: "haste", example: "The new policy addresses the impact of fuss in modern society." },
  { english: "gaol", turkish: "hapishane", synonym: "prison", example: "The new policy addresses the impact of gaol in modern society." },
  { english: "gear", turkish: "vites", synonym: "gear", example: "The new policy addresses the impact of gear in modern society." },
  { english: "germ", turkish: "mikrop", synonym: "microbe", example: "The new policy addresses the impact of germ in modern society." },
  { english: "ghost", turkish: "hayalet", synonym: "ghost", example: "The new policy addresses the impact of ghost in modern society." },
  { english: "ginger", turkish: "zencefil", synonym: "ginger", example: "The new policy addresses the impact of ginger in modern society." },
  { english: "globe", turkish: "küre", synonym: "sphere", example: "The new policy addresses the impact of globe in modern society." },
  { english: "glue", turkish: "yapıştırıcı", synonym: "adhesive", example: "The new policy addresses the impact of glue in modern society." },
  { english: "goal", turkish: "hedef", synonym: "target", example: "The new policy addresses the impact of goal in modern society." },
  { english: "gossip", turkish: "dedikodu", synonym: "rumor", example: "The new policy addresses the impact of gossip in modern society." },
  { english: "grapefruit", turkish: "greyfurt", synonym: "grapefruit", example: "The new policy addresses the impact of grapefruit in modern society." },
  { english: "grateful", turkish: "minnettar", synonym: "thankful", example: "The new policy addresses the impact of grateful in modern society." },
  { english: "gravestone", turkish: "mezartaşı", synonym: "gravestone", example: "The new policy addresses the impact of gravestone in modern society." },
  { english: "graveyard", turkish: "mezarlık", synonym: "graveyard", example: "It is essential to adopt a graveyard perspective during the evaluation." },
  { english: "greengrocer", turkish: "manav", synonym: "greengrocer", example: "The new policy addresses the impact of greengrocer in modern society." },
  { english: "groom", turkish: "damat", synonym: "groom", example: "The new policy addresses the impact of groom in modern society." },
  { english: "grumble", turkish: "sızlanmak", synonym: "grunt", example: "Scientists are trying to grumble the primary causes of this phenomenon." },
  { english: "guarantee", turkish: "garanti", synonym: "guarantee", example: "The new policy addresses the impact of guarantee in modern society." },
  { english: "guided missile", turkish: "güdümlü füze", synonym: "guided missile", example: "The new policy addresses the impact of guided missile in modern society." },
  { english: "gulf", turkish: "körfez", synonym: "gulf", example: "The new policy addresses the impact of gulf in modern society." },
  { english: "guy", turkish: "adam", synonym: "guy", example: "The new policy addresses the impact of guy in modern society." },
  { english: "habitat", turkish: "doğal yuva", synonym: "habitat", example: "The new policy addresses the impact of habitat in modern society." },
  { english: "hairdresser", turkish: "berber", synonym: "coiffeur", example: "The new policy addresses the impact of hairdresser in modern society." },
  { english: "hairdryer", turkish: "saç kurutma makinesi", synonym: "hairdryer", example: "Scientists are trying to hairdryer the primary causes of this phenomenon." },
  { english: "halt", turkish: "durma", synonym: "stop", example: "The new policy addresses the impact of halt in modern society." },
  { english: "ham", turkish: "jambon", synonym: "ham", example: "The new policy addresses the impact of ham in modern society." },
  { english: "hand grenade", turkish: "el bombası", synonym: "hand grenade", example: "The new policy addresses the impact of hand grenade in modern society." },
  { english: "handicap", turkish: "sakat", synonym: "obstacle", example: "The new policy addresses the impact of handicap in modern society." },
  { english: "hang on", turkish: "beklemek", synonym: "wait", example: "Scientists are trying to hang on the primary causes of this phenomenon." },
  { english: "happen", turkish: "olmak", synonym: "become", example: "Scientists are trying to happen the primary causes of this phenomenon." },
  { english: "headquarters", turkish: "karargah", synonym: "headquarters", example: "The new policy addresses the impact of headquarters in modern society." },
  { english: "headline", turkish: "başlık", synonym: "cuff", example: "It is essential to adopt a headline perspective during the evaluation." },
  { english: "headphone", turkish: "kulaklık", synonym: "headset", example: "It is essential to adopt a headphone perspective during the evaluation." },
  { english: "hectare", turkish: "hektar", synonym: "hectare", example: "The new policy addresses the impact of hectare in modern society." },
  { english: "heritage", turkish: "miras", synonym: "legacy", example: "The new policy addresses the impact of heritage in modern society." },
  { english: "hinge", turkish: "destek", synonym: "rest", example: "The new policy addresses the impact of hinge in modern society." },
  { english: "hold on", turkish: "bekle", synonym: "hang on", example: "The new policy addresses the impact of hold on in modern society." },
  { english: "holy", turkish: "kutsal", synonym: "sacred", example: "It is essential to adopt a holy perspective during the evaluation." },
  { english: "hook", turkish: "çengel", synonym: "hanger", example: "The new policy addresses the impact of hook in modern society." },
  { english: "horizontal", turkish: "yatay", synonym: "horizontal", example: "The new policy addresses the impact of horizontal in modern society." },
  { english: "hose", turkish: "hortum", synonym: "tornado", example: "The new policy addresses the impact of hose in modern society." },
  { english: "hubbub", turkish: "gürültü", synonym: "noise", example: "The new policy addresses the impact of hubbub in modern society." },
  { english: "hug", turkish: "sarılmak", synonym: "cuddle", example: "Scientists are trying to hug the primary causes of this phenomenon." },
  { english: "huge", turkish: "çok büyük", synonym: "giant", example: "The new policy addresses the impact of huge in modern society." },
  { english: "human", turkish: "insan", synonym: "human", example: "The new policy addresses the impact of human in modern society." },
  { english: "hush", turkish: "sakinlik", synonym: "tranquility", example: "It is essential to adopt a hush perspective during the evaluation." },
  { english: "hut", turkish: "kulübe", synonym: "shed", example: "The new policy addresses the impact of hut in modern society." },
  { english: "idiot", turkish: "aptal", synonym: "idiot", example: "The new policy addresses the impact of idiot in modern society." },
  { english: "ignition", turkish: "tutuşma", synonym: "combustion", example: "The new policy addresses the impact of ignition in modern society." },
  { english: "ignore", turkish: "önemsememek", synonym: "disregard", example: "Scientists are trying to ignore the primary causes of this phenomenon." },
  { english: "illustrate", turkish: "resimle göstermek", synonym: "illustrate", example: "Scientists are trying to illustrate the primary causes of this phenomenon." },
  { english: "imagination", turkish: "tasavvur", synonym: "imagination", example: "The new policy addresses the impact of imagination in modern society." },
  { english: "imagine", turkish: "hayal etmek", synonym: "dream", example: "Scientists are trying to imagine the primary causes of this phenomenon." },
  { english: "imitate", turkish: "örnek almak", synonym: "copy", example: "Scientists are trying to imitate the primary causes of this phenomenon." },
  { english: "imitation", turkish: "taklit", synonym: "mimic", example: "The new policy addresses the impact of imitation in modern society." },
  { english: "immoral", turkish: "ahlaksız", synonym: "depraved", example: "It is essential to adopt a immoral perspective during the evaluation." },
  { english: "impair", turkish: "bozmak", synonym: "disrupt", example: "Scientists are trying to impair the primary causes of this phenomenon." },
  { english: "implement", turkish: "yürürlüğe koymak", synonym: "apply", example: "Scientists are trying to implement the primary causes of this phenomenon." },
  { english: "imply", turkish: "ima etme", synonym: "allude to", example: "The new policy addresses the impact of imply in modern society." },
  { english: "impress", turkish: "etkilemek", synonym: "affect", example: "Scientists are trying to impress the primary causes of this phenomenon." },
  { english: "impressive", turkish: "etkileyici", synonym: "fascinating", example: "The new policy addresses the impact of impressive in modern society." },
  { english: "incentive", turkish: "teşvik", synonym: "incentive", example: "The new policy addresses the impact of incentive in modern society." },
  { english: "incidentally", turkish: "bunun yanında", synonym: "by the way", example: "The new policy addresses the impact of incidentally in modern society." },
  { english: "indefinite", turkish: "belirsiz", synonym: "uncertain", example: "It is essential to adopt a indefinite perspective during the evaluation." },
  { english: "indefinitely", turkish: "sonsuz", synonym: "indefinitely", example: "It is essential to adopt a indefinitely perspective during the evaluation." },
  { english: "indemnify", turkish: "tazminat ödemek", synonym: "indemnify", example: "Scientists are trying to indemnify the primary causes of this phenomenon." },
  { english: "indemnity", turkish: "tazminat", synonym: "indemnify", example: "The new policy addresses the impact of indemnity in modern society." },
  { english: "individual", turkish: "birey", synonym: "person", example: "The new policy addresses the impact of individual in modern society." },
  { english: "indorse", turkish: "onaylamak", synonym: "confirm", example: "Scientists are trying to indorse the primary causes of this phenomenon." },
  { english: "endorsement", turkish: "onay", synonym: "confirmation", example: "The new policy addresses the impact of endorsement in modern society." },
  { english: "inevitable", turkish: "kaçınılmaz", synonym: "unavoidable", example: "The new policy addresses the impact of inevitable in modern society." },
  { english: "infinite", turkish: "sonsuz", synonym: "endless", example: "It is essential to adopt a infinite perspective during the evaluation." },
  { english: "inflammable", turkish: "yanıcı", synonym: "flammable", example: "The new policy addresses the impact of inflammable in modern society." },
  { english: "inflate", turkish: "şişirmek", synonym: "puff up", example: "Scientists are trying to inflate the primary causes of this phenomenon." },
  { english: "inflation", turkish: "enflasyon", synonym: "inflation", example: "The new policy addresses the impact of inflation in modern society." },
  { english: "inflexible", turkish: "bükülmez", synonym: "inflexible", example: "The new policy addresses the impact of inflexible in modern society." },
  { english: "initial", turkish: "birinci", synonym: "first", example: "The new policy addresses the impact of initial in modern society." },
  { english: "initiative", turkish: "başlatma", synonym: "initiatory", example: "The new policy addresses the impact of initiative in modern society." },
  { english: "inject", turkish: "iğne yapmak", synonym: "syringe", example: "Scientists are trying to inject the primary causes of this phenomenon." },
  { english: "innocent", turkish: "suçsuz", synonym: "blameless", example: "It is essential to adopt a innocent perspective during the evaluation." },
  { english: "insecure", turkish: "emniyetsiz", synonym: "distrustful", example: "It is essential to adopt a insecure perspective during the evaluation." },
  { english: "insolvent", turkish: "müflis", synonym: "bankrupt", example: "The new policy addresses the impact of insolvent in modern society." },
  { english: "inspire", turkish: "ilham vermek", synonym: "reveal", example: "Scientists are trying to inspire the primary causes of this phenomenon." },
  { english: "instant", turkish: "hızlı", synonym: "instant", example: "It is essential to adopt a instant perspective during the evaluation." },
  { english: "insulate", turkish: "izole etmek", synonym: "isolate", example: "Scientists are trying to insulate the primary causes of this phenomenon." },
  { english: "insult", turkish: "hakaret etme", synonym: "give affront to", example: "The new policy addresses the impact of insult in modern society." },
  { english: "intangible", turkish: "manevi", synonym: "spiritual", example: "The new policy addresses the impact of intangible in modern society." },
  { english: "intense", turkish: "yoğun", synonym: "busy", example: "The new policy addresses the impact of intense in modern society." },
  { english: "intensive", turkish: "yoğun", synonym: "dense", example: "The new policy addresses the impact of intensive in modern society." },
  { english: "interfere", turkish: "müdahale etme", synonym: "interfere", example: "The new policy addresses the impact of interfere in modern society." },
  { english: "intestines", turkish: "bağırsaklar", synonym: "entrails", example: "The new policy addresses the impact of intestines in modern society." },
  { english: "invade", turkish: "istila etmek", synonym: "invade", example: "Scientists are trying to invade the primary causes of this phenomenon." },
  { english: "invoice", turkish: "fatura", synonym: "bill", example: "The new policy addresses the impact of invoice in modern society." },
  { english: "involve", turkish: "içermek", synonym: "include", example: "Scientists are trying to involve the primary causes of this phenomenon." },
  { english: "ironically", turkish: "inadına", synonym: "ironically", example: "The new policy addresses the impact of ironically in modern society." },
  { english: "irritate", turkish: "kızdırmak", synonym: "make angry", example: "Scientists are trying to irritate the primary causes of this phenomenon." },
  { english: "itch", turkish: "kaşındırmak", synonym: "irritate", example: "Scientists are trying to itch the primary causes of this phenomenon." },
  { english: "item", turkish: "birim", synonym: "piece", example: "The new policy addresses the impact of item in modern society." },
  { english: "jack", turkish: "torpil yaptırmak", synonym: "pull strings", example: "Scientists are trying to jack the primary causes of this phenomenon." },
  { english: "jackal", turkish: "çakal", synonym: "jackal", example: "The new policy addresses the impact of jackal in modern society." },
  { english: "jar", turkish: "kavanoz", synonym: "jar", example: "The new policy addresses the impact of jar in modern society." },
  { english: "jeans", turkish: "kot pantolon", synonym: "jeans", example: "The new policy addresses the impact of jeans in modern society." },
  { english: "jelly", turkish: "jöle", synonym: "jelly", example: "The new policy addresses the impact of jelly in modern society." },
  { english: "jellyfish", turkish: "denizanası", synonym: "jellyfish", example: "The new policy addresses the impact of jellyfish in modern society." },
  { english: "keen", turkish: "keskin", synonym: "sharp", example: "The new policy addresses the impact of keen in modern society." },
  { english: "kidnap", turkish: "zorla kaçırmak", synonym: "abduct", example: "Scientists are trying to kidnap the primary causes of this phenomenon." },
  { english: "kidney", turkish: "böbrek", synonym: "kidney", example: "The new policy addresses the impact of kidney in modern society." },
  { english: "kin", turkish: "aile", synonym: "family", example: "The new policy addresses the impact of kin in modern society." },
  { english: "knight", turkish: "şovalye", synonym: "chevalier", example: "The new policy addresses the impact of knight in modern society." },
  { english: "knob", turkish: "tokmak", synonym: "mallet", example: "Scientists are trying to knob the primary causes of this phenomenon." },
  { english: "label", turkish: "etiket", synonym: "label", example: "The new policy addresses the impact of label in modern society." },
  { english: "ladle", turkish: "kepçe", synonym: "scoop", example: "The new policy addresses the impact of ladle in modern society." },
  { english: "lampshade", turkish: "sokak lambası", synonym: "lampshade", example: "The new policy addresses the impact of lampshade in modern society." },
  { english: "lane", turkish: "dar yol", synonym: "alley", example: "The new policy addresses the impact of lane in modern society." },
  { english: "lash", turkish: "kamçı", synonym: "stripe", example: "The new policy addresses the impact of lash in modern society." },
  { english: "launch", turkish: "bir şeye başlamak", synonym: "start", example: "Scientists are trying to launch the primary causes of this phenomenon." },
  { english: "laundry-basket", turkish: "çamaşır sepeti", synonym: "laundry-basket", example: "The new policy addresses the impact of laundry-basket in modern society." },
  { english: "leauge", turkish: "birlik", synonym: "leauge", example: "It is essential to adopt a leauge perspective during the evaluation." },
  { english: "leak", turkish: "akıntı", synonym: "seepage", example: "The new policy addresses the impact of leak in modern society." },
  { english: "lease", turkish: "kiralama", synonym: "hire", example: "The new policy addresses the impact of lease in modern society." },
  { english: "lecture", turkish: "ders", synonym: "lecture", example: "The new policy addresses the impact of lecture in modern society." },
  { english: "length", turkish: "uzunluk", synonym: "length", example: "The new policy addresses the impact of length in modern society." },
  { english: "lettuce", turkish: "marul", synonym: "lettuce", example: "The new policy addresses the impact of lettuce in modern society." },
  { english: "lever", turkish: "kaldıraç", synonym: "pry", example: "The new policy addresses the impact of lever in modern society." },
  { english: "liar", turkish: "yalancı", synonym: "liar", example: "The new policy addresses the impact of liar in modern society." },
  { english: "lick", turkish: "yalamak", synonym: "lick", example: "Scientists are trying to lick the primary causes of this phenomenon." },
  { english: "lid", turkish: "kapak", synonym: "cover", example: "The new policy addresses the impact of lid in modern society." },
  { english: "lighter", turkish: "çakmak", synonym: "lighter", example: "Scientists are trying to lighter the primary causes of this phenomenon." },
  { english: "limit", turkish: "limit", synonym: "limit", example: "The new policy addresses the impact of limit in modern society." },
  { english: "liquidate", turkish: "başından atmak", synonym: "get rid of", example: "Scientists are trying to liquidate the primary causes of this phenomenon." },
  { english: "literature", turkish: "edebiyat", synonym: "literature", example: "The new policy addresses the impact of literature in modern society." },
  { english: "litter", turkish: "çöp", synonym: "garbage", example: "The new policy addresses the impact of litter in modern society." },
  { english: "liver", turkish: "karaciğer", synonym: "liver", example: "The new policy addresses the impact of liver in modern society." },
  { english: "loaf", turkish: "bütün ekmek", synonym: "loaf", example: "Scientists are trying to loaf the primary causes of this phenomenon." },
  { english: "loaf", turkish: "vakti boşa geçirmek", synonym: "not to work", example: "Scientists are trying to loaf the primary causes of this phenomenon." },
  { english: "loan", turkish: "ödünç vermek", synonym: "lending", example: "Scientists are trying to loan the primary causes of this phenomenon." },
  { english: "lobster", turkish: "istakoz", synonym: "lobster", example: "The new policy addresses the impact of lobster in modern society." },
  { english: "locate", turkish: "kurmak", synonym: "locate", example: "Scientists are trying to locate the primary causes of this phenomenon." },
  { english: "lonely", turkish: "yalnız", synonym: "alone", example: "The new policy addresses the impact of lonely in modern society." },
  { english: "lorry", turkish: "kamyon", synonym: "truck", example: "The new policy addresses the impact of lorry in modern society." },
  { english: "loyal", turkish: "sadık", synonym: "faithful", example: "The new policy addresses the impact of loyal in modern society." },
  { english: "loyalty", turkish: "sadakat", synonym: "devotion", example: "The new policy addresses the impact of loyalty in modern society." },
  { english: "magazine", turkish: "cephanelik", synonym: "arsenal", example: "It is essential to adopt a magazine perspective during the evaluation." },
  { english: "magazine", turkish: "magazin", synonym: "journal", example: "The new policy addresses the impact of magazine in modern society." },
  { english: "magnet", turkish: "mıktanıs", synonym: "magnet", example: "The new policy addresses the impact of magnet in modern society." },
  { english: "magnificent", turkish: "ihtişam", synonym: "pompous", example: "The new policy addresses the impact of magnificent in modern society." },
  { english: "magnifying-glass", turkish: "büyüteç", synonym: "magnifying-glass", example: "The new policy addresses the impact of magnifying-glass in modern society." },
  { english: "maid", turkish: "kadın hizmetçi", synonym: "maid", example: "The new policy addresses the impact of maid in modern society." },
  { english: "maintain", turkish: "bakım onarım", synonym: "repair", example: "The new policy addresses the impact of maintain in modern society." },
  { english: "major", turkish: "önemli", synonym: "major", example: "It is essential to adopt a major perspective during the evaluation." },
  { english: "majority", turkish: "çoğunluk", synonym: "majority", example: "The new policy addresses the impact of majority in modern society." },
  { english: "maniac", turkish: "manyak", synonym: "maniac", example: "The new policy addresses the impact of maniac in modern society." },
  { english: "manual", turkish: "el ile yapılan", synonym: "manual", example: "The new policy addresses the impact of manual in modern society." },
  { english: "manufacture", turkish: "üretmek", synonym: "produce", example: "Scientists are trying to manufacture the primary causes of this phenomenon." },
  { english: "margin", turkish: "katkı", synonym: "margin", example: "The new policy addresses the impact of margin in modern society." },
  { english: "marmalade", turkish: "marmelat", synonym: "marmalade", example: "The new policy addresses the impact of marmalade in modern society." },
  { english: "massacre", turkish: "katliam", synonym: "slaughter", example: "The new policy addresses the impact of massacre in modern society." },
  { english: "massive", turkish: "çok büyük ve ağır", synonym: "large", example: "The new policy addresses the impact of massive in modern society." },
  { english: "mat", turkish: "paspas", synonym: "mop", example: "The new policy addresses the impact of mat in modern society." },
  { english: "mate", turkish: "arkadaş", synonym: "friend", example: "The new policy addresses the impact of mate in modern society." }
  { english: "strange", turkish: "tuhaf", synonym: "odd", example: "Bugün ikimizin de aynı gömleği giymiş olması garip bir tesadüftü" }
  { english: "injure", turkish: "yaralanmak", synonym: "odd", example: "Dünkü futbol maçında dizinden yaralandı." }
  { english: "pressure", turkish: "baskı", synonym: "pressure", example: "Sınav yaklaştıkça üzerindeki baskı daha da artmaya başladı." }
  { english: "epidemic", turkish: "salgın", synonym: "contagious", example: "Hijyen kurallarına uymak, bulaşıcı salgınların önüne geçmedeki en etkili yöntemdir." }
  { english: "consequence", turkish: "sonuç", synonym: "pressure", example: "Sınavın sonuçları açıklanınca herkes derin bir nefes aldı." }
  { english: "defect", turkish: "kusur", synonym: "pressure", example: "Kazada karşı tarafın asli kusurlu olduğu polis raporuyla kesinleşti." }
  { english: "give up", turkish: "vazgeçmek", synonym: "forego", example: "Bütün engellere rağmen hedeflerinden asla vazgeçmedi." }
  { english: "waste", turkish: "boşa harcamak", synonym: "forego", example: "Bütün günü sosyal medyada gezinerek boşa harcadı." }
  { english: "reject", turkish: "reddetmek", synonym: "refuse", example: "Şirketten gelen cazip iş teklifini nazikçe reddetti." }
  { english: "generally", turkish: "genellikle", synonym: "in general", example: "Hafta sonları genellikle erken kalkıp uzun bir yürüyüşe çıkarım." }
  { english: "occasionally", turkish: "ara ara", synonym: "sometimes", example: "Yıllar geçmesine rağmen o güzel günleri ara ara hatırlar ve gülüserim." }
  { english: "rarely", turkish: "nadiren", synonym: "seldom", example: "Sağlık sorunları dışında toplantılarını nadiren aksatır." }
  { english: "look for", turkish: "aramak", synonym: "research", example: "Günlerdir kaybettiği önemli evrakı her yerde arıyor." }
  { english: "urban", turkish: "kentsel", synonym: "urban", example: "Kediler kentsel alanlarda kolayca yaşar." }
  { english: "prohibit", turkish: "yasaklamak", synonym: "proscribe", example: "Doktor, tatlı yemesini yasakladı." }
  { english: "infrared", turkish: "kızılötesi", synonym: "infrared", example: "Gece görüş kameraları kızılötesi ışık kullanır." }
  { english: "rural", turkish: "kırsal", synonym: "rustic", example: "Kırsal alanlarda hava çok temizdir." }
  { english: "dormitory", turkish: "yurt", synonym: "dormitory", example: "Öğrenciler yeni öğretim yılında yurtta kalacak." }
  { english: "underestimate", turkish: "önemsememek", synonym: "underestimate", example: "Söylenen kötü sözleri hiç önemsemedi." }
  { english: "pollution", turkish: "kirlilik", synonym: "pollution", example: "Fabrikalar hava kirliliğine neden olur." }
  { english: "suffer", turkish: "acı çekmek", synonym: "be in pain", example: "Hastalığı yüzünden aylarca acı çekti." }
  { english: "assignment", turkish: "ödev", synonym: "homework", example: "Zor ödevler için arkadaşımdan yardım istedim." }
  { english: "anchorman", turkish: "sunucu", synonym: "anchorman", example: "Televizyon sunucusu programı neşeyle başlattı." }
  { english: "exact", turkish: "aynı", synonym: "exact", example: "İki elbisenin rengi ve kesimi birebir aynı." }
  { english: "measure", turkish: "tedbir", synonym: "precaution", example: "Virüse karşı gerekli tedbirleri aldık." }
  { english: "raise", turkish: "artırmak", synonym: "increase", example: "Spor yapmak vücut direncini artırır." }
  { english: "deer", turkish: "geyik", synonym: "deer", example: "Ormanda aniden güzel bir geyik belirdi." }
  { english: "recently", turkish: "şimdiye kadar", synonym: "until now", example: "Şimdiye kadar okuduğum en etkileyici kitaptı." }
  { english: "approve", turkish: "onaylamak", synonym: "confirm", example: "Üyeliğinizi tamamlamak için gelen e-postayı onaylamanız gerekiyor." }
  { english: "diagnose", turkish: "teşhis etmek", synonym: "diagnose", example: "Erken aşamada teşhis edilen rahatsızlıkların tedavisi daha kolaydır." }
  { english: "recruit", turkish: "işe almak", synonym: "recruit", example: "Şirket yeni proje için üç yazılımcı işe aldı." }
  { english: "decline", turkish: "azalmak", synonym: "decrease", example: "Son birkaç yılda hava kirliliği oranı belirgin şekilde azaldı." }
  { english: "crowd", turkish: "kalabalık", synonym: "horde", example: "Meydandaki kalabalık konser başladıktan sonra iyice arttı." }
  { english: "choose", turkish: "seçmek", synonym: "select", example: "Yarın yapılacak seçimde yeni sınıf başkanını seçeceğiz." }
  { english: "thief", turkish: "hırsız", synonym: "burglar", example: "Gece vakti dükkana giren hırsız alarm çalınca kaçtı." }
  { english: "aware of", turkish: "farkında olmak", synonym: "aware of", example: "Yaptığı hatanın büyüklüğünün sonradan farkında oldu." }
  { english: "responsibility", turkish: "sorumluluk", synonym: "liability", example: "Yeni projenin tüm sorumluluğunu üzerine aldı." }
  { english: "extinction", turkish: "nesli tükenme", synonym: "disappearance", example: "Bilim insanları nesli tükenme riski yüksek olan bitki türlerini koruma altına aldı." }
  { english: "accident", turkish: "kaza", synonym: "crash", example: "Otoyolda meydana gelen kaza yüzünden trafik saatlerce aksadı." }
  { english: "discuss", turkish: "tartışmak", synonym: "debate", example: "İki uzman canlı yayında ekonomi politikalarını tartıştı." }
  { english: "expect", turkish: "ummak", synonym: "hope", example: "Bütün bu çabalarımızın karşılığını yakın zamanda almayı umuyorum." }
  { english: "patient", turkish: "hasta", synonym: "case", example: "Hasta adam ilaçlarını aldıktan sonra dinlenmeye çekildi." }
  { english: "establish", turkish: "kurmak", synonym: "set up", example: "İki girişimci ortak olarak yeni bir şirket kurdu." }
  { english: "inform", turkish: "bilgi vermek", synonym: "acquaint", example: "Müşteri temsilcisi yeni kampanya hakkında detaylı bilgi verdi." }
  { english: "blow", turkish: "esmek", synonym: "blow", example: "Gece boyunca denizden tatlı ve serin bir rüzgâr esti." }
  { english: "rest", turkish: "dinlenme", synonym: "relaxation", example: "Yoğun geçen bir haftanın ardından iyi bir dinlenme şart oldu." }
  { english: "submit", turkish: "teslim etmek", synonym: "deliver", example: "Kargo görevlisi paketi eve teslim etti." }
  { english: "mend", turkish: "tamir etmek", synonym: "repair", example: "Ustalar bozulan çamaşır makinesini tamir ediyor." }
  { english: "distance", turkish: "mesafe", synonym: "distance", example: "İki şehir arasındaki mesafe oldukça uzundu." }
  { english: "digestive", turkish: "sindirimsel", synonym: "digestive", example: "Yoğurt yemek, sindirimsel sağlığı destekler." }
  { english: "disorder", turkish: "hastalık", synonym: "illness", example: "Bakteriler, ciddi sindirimsel hastalıklara yol açabilir." }
  { english: "promote", turkish: "geliştirmek", synonym: "improve", example: "Kendini geliştirmek için her gün yeni bir şeyler öğreniyor." }
  { english: "side effect", turkish: "yan etki", synonym: "repercussion", example: "Bu ilacın hiçbir yan etkisi yok." }
  { english: "provide", turkish: "sağlamak", synonym: "ensure", example: "Düzenli uyumak, gün boyu enerjik olmanı sağlar." }
  { english: "participant", turkish: "katılımcı", synonym: "subscriber", example: "Eğitimi başarıyla tamamlayan her katılımcıya sertifika verildi." }
  { english: "stem cell", turkish: "kök hücre", synonym: "stem cell", example: "Nakil yapılan kök hücreler, hastanın iyileşme sürecini önemli ölçüde hızlandırdı." }
  { english: "approach", turkish: "yaklaşmak", synonym: "come close to", example: "Sınav tarihi yaklaştıkça heyecanı daha da arttı." }
  { english: "attractive", turkish: "çekici", synonym: "appealing", example: "Mıknatısın metaller üzerindeki çekici gücü denetlendi." }
  { english: "labour", turkish: "emek", synonym: "labour", example: "Büyük bir emek vererek hazırladığı proje ödül kazandı." }
  { english: "entertaining", turkish: "eğlenceli", synonym: "enjoyable", example: "Dün akşam ailece çok eğlenceli bir film izledik." }
  { english: "salary", turkish: "maaş", synonym: "wage", example: "Ay başında maaşı yatınca hemen faturaları ödedi." }
  { english: "carry", turkish: "taşımak", synonym: "transport", example: "Kütüphaneden aldığı ağır kitapları çantasında taşımak onu biraz yordu." }
  { english: "employee", turkish: "çalışan", synonym: "staff member", example: "Gece vardiyasında çalışan personeller için servis imkanı sunuluyor." }
];
